name: CICD
on: push
jobs:
  build-jobs:
       runs-on: ubuntu-latest
       steps:
         - name: Run many tests
           run: echo "build job"
  test-jobs:
       runs-on: ubuntu-latest
       steps:
         - name: Run many tests
           run: echo "test job"
  deploy-jobs:
       runs-on: ubuntu-latest
       steps:
         - name: Run many tests
           run: echo "deploy job"           